Repository openebs/openebsctl, pull requests merged in 2021-06, with the labels that each got.

#27 [bug]handle exception when cva is not present.
  kubectl-openebs/cli/command/describe/pvc_info.go
  kubectl-openebs/cli/command/describe/volume_info.go
  kubectl-openebs/cli/command/get/volume_list.go
  kubectl-openebs/cli/util/checks.go
  kubectl-openebs/cli/util/checks_test.go
  kubectl-openebs/cli/util/constant.go
Labels: bug

#28 Add support to list jiva volumes along with CStor volumes
  client/k8s.go
  go.mod
  go.sum
  kubectl-openebs/cli/command/get/get.go
  kubectl-openebs/cli/command/get/volume_list.go
  kubectl-openebs/cli/util/constant.go
Labels: enhancement

#30 doc(release): README and CHANGELOG changes for release v0.1.0
  CHANGELOG.md
  README.md
Labels: documentation
